### ISSUE TITLE
Create API endpoints for job applications

### ISSUE THREAD

**Issue by rm004** [Code-Crusaders-00/CareerPath-Pro#15]
Make GET endpoint to display applications page

**Comment by navanchauhan** [comment]
Job Applications endpoint:
* GET /users/{userId}/job-applications - Retrieve all job applications for a user.
* POST /users/{userId}/job-applications - Add a new job application for a user.
* GET /users/{userId}/job-applications/{applicationId} - Retrieve details of a specific job application.
* PUT /users/{userId}/job-applications/{applicationId} - Update a specific job application.
* DELETE /users/{userId}/job-applications/{applicationId} - Delete a specific job application.
