### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by charlottehauke** [Code-Crusaders-00/CareerPath-Pro#4]
The database will allow users to store the information they input into the application. Different elements that will be stored include user information, job applications, possibly a resume, etc.

**Comment by navanchauhan** [comment]
1st Table: Authentication 
* Primary Key
* User
* Password_Hash
* Email
* Name 

2nd Job Application Status
* Primary Key
* Owned By - > Linked to User
* Last Updated At
* Created At
* Company Name
* Job Description 
* URL
* Current Status

Table 3: Job Application
* Primary Key
* Company
* Job Title
* Posted At
* URL
* Description
