### ISSUE TITLE
Work on ejs files

### ISSUE THREAD

**Issue by charlottehauke** [Code-Crusaders-00/CareerPath-Pro#7]
Implement the ejs files to allow an efficient implementation of crucial page content.

**Comment by navanchauhan** [comment]
Pages/Partials we need:
- [ ] Login Page
- [ ] Register Page
- [ ] Landing Page (If we wanted another page rather than defaulting to the login page)
- [ ] User Dashboard
    - Application Tracker Preview
    - Suggested Jobs Preview
- [ ] Application Tracker
    - New Application Modal
    - Edit Application Modal
    - List of Applications
- [ ] Suggested Jobs
    - List of Jobs
